version: "3"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: paulo
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: service-system
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - /path/on/host:/var/lib/mysql
